export const ADDED = "todo/add"
export const TOGGLED = "todo/toggled"
export const COLOURSELECTED = "todo/colourSelected"
export const DELETED = "todo/deleted"
export const ALLCOMPLETED = "todo/allCompleted"
export const CLEARCOMPLETED = "todo/clearCompleted"